### ISSUE TITLE
Background pattern

### ISSUE THREAD

**Issue by geftimov** [johncarpenter/AndroidFramework#2]
It is not a issue , just a question.
How did you generate this vector drawable:
[background_pattern.xml](https://github.com/johncarpenter/AndroidFramework/blob/jc/ux_login/app/src/main/res/drawable/background_pattern.xml)

**Comment by johncarpenter** [comment]
I generated the SVG using this tool; 
http://qrohlf.com/trianglify-generator/

and created the vector drawable using
http://inloop.github.io/svg2android/

The second is a great tool for  converting any SVG.

**Comment by geftimov** [comment]
Thanks very much,
I am using the second tool daily.
But the first was really good for my purposes.

Sorry for opening a issue, but didn't know how to contact you.
Closing it now.
